<?php

function custom_menu() {
 $items = array();
 $items['custom'] = array (
      'title' => t('My Article'),
      'page callback' => 'custom_list',
      'access arguments' => array('access content'),
      );
   return $items;
 }
function custom_list() {
     
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->propertyOrderBy('created', 'DESC')
        ->range(0, 10);
        

  $result = $query->execute();



  if(isset($result['node'])) {

      $custom_items_nids = array_keys($result['node']);
      $custom_items = entity_load('node',$custom_items_nids);
  }
  
  $output = "<ul>\n";
  foreach($custom_items as $custom_item){
   $snippet = "<li>\n";
   $snippet .= "<h2>".t($custom_item->title)."</h2>\n";
   $snippet .= "<p>".t(substr($custom_item->body['und'][0]['value'],0, 600))."</p>\n";
   $snippet .= "<li>\n";
   $output .= $snippet;
 }
   
   $output .= "<ul>\n";

  $pager = theme('pager', array("quantity" => 3));
  $output = theme('custom_list', array('items' => $results));
  $output = $output . $pager;
 
   
   return $output;

  

}



 

  
